### ISSUE TITLE
Online editor is unable to compile macros

### ISSUE THREAD

**Issue by andreypopp** [sweet-js/sweet-core#117]
It just shows "Error: expecting a pattern surrounded by {} in syntax case"

http://sweetjs.org/browser/editor.html

**Comment by juliankrispel** [comment]
Are the examples on the homepage still not using the new syntax? Here's an example, it throws an error:

```
macro id {
  case ($x) => { $x }
}
```

I'd be happy to help updating them.

**Comment by disnet** [comment]
Where did you find that one? It's not even valid old syntax.

**Comment by juliankrispel** [comment]
Oh, these must be a bunch of [old github pages](http://voila.github.io/sweet.js/), my bad. Confusing though.
