### ISSUE TITLE
Macros on function's parameters

### ISSUE THREAD

**Issue by amatiasq** [sweet-js/sweet-core#212]
I'm trying to write function parameter's type using C++ like notation

```
function Something(String signal, Number value) { }
```

To produce

```
function Something(signal, value) { }
```

So I create a function macro and a helper for the parameters

```
macro params_helper {
  rule { $type:ident $name:ident , $rest ... } => {
    $name , params_helper $rest ...
  }
  rule { $name:ident , $rest ... } => {
    $name , params_helper $rest ...
  }
  rule { $type:ident $name:ident } => { $name }
  rule { $name:ident } => { $name }
}

let function = macro {
  rule { $name ($params ...) $body } => {
    function $name(params_helper $params ...) $body
  }
}

function Something(String signal) { }
```

And it produces this result: <a href="http://sweetjs.org/browser/editor.html#macro%20params_helper%20%7B%0A%20%20rule%20%7B%20$type:ident%20$name:ident%20,%20$rest%20...%20%7D%20=%3E%20%7B%0A%20%20%20%20$name%20,%20params_helper%20$rest%20...%0A%20%20%7D%0A%20%20rule%20%7B%20$name:ident%20,%20$rest%20...%20%7D%20=%3E%20%7B%0A%20%20%20%20$name%20,%20params_helper%20$rest%20...%0A%20%20%7D%0A%20%20rule%20%7B%20$type:ident%20$name:ident%20%7D%20=%3E%20%7B%20$name%20%7D%0A%20%20rule%20%7B%20$name:ident%20%7D%20=%3E%20%7B%20$name%20%7D%0A%7D%0A%0Alet%20function%20=%20macro%20%7B%0A%20%20rule%20%7B%20$name%20($params%20...)%20$body%20%7D%20=%3E%20%7B%0A%20%20%20%20function%20$name(params_helper%20$params%20...)%20$body%0A%20%20%7D%0A%7D%0A%0Afunction%20Something(String%20signal)%20%7B%20%7D">Test it</a>

```
function Something$5523(params_helper$5524, String$5525, signal$5526) { }
```

I don't understand why a comma is placed here but anyway I try to move `function` to a helper so `params_helper` is parsed but it produces the same result since `function_helper` is parsed before `params_helper`. <a href="http://sweetjs.org/browser/editor.html#macro%20params_helper%20%7B%0A%20%20rule%20%7B%20$type:ident%20$name:ident%20,%20$rest%20...%20%7D%20=%3E%20%7B%0A%20%20%20%20$name%20,%20params_helper%20$rest%20...%0A%20%20%7D%0A%20%20rule%20%7B%20$name:ident%20,%20$rest%20...%20%7D%20=%3E%20%7B%0A%20%20%20%20$name%20,%20params_helper%20$rest%20...%0A%20%20%7D%0A%20%20rule%20%7B%20$type:ident%20$name:ident%20%7D%20=%3E%20%7B%20$name%20%7D%0A%20%20rule%20%7B%20$name:ident%20%7D%20=%3E%20%7B%20$name%20%7D%0A%7D%0A%0Amacro%20function_helper%20%7B%0A%20%20rule%20%7B%20$name%20($params%20...)%20$body%20%7D%C2%A0=%3E%20%7B%0A%20%20%20%20function%20$name%20($params%20...)%20$body%0A%20%20%7D%0A%7D%0A%0Alet%20function%20=%20macro%20%7B%0A%20%20rule%20%7B%20$name%20($params%20...)%20$body%20%7D%20=%3E%20%7B%0A%20%20%20%20function_helper%20$name(params_helper%20$params%20...)%20$body%0A%20%20%7D%0A%7D%0A%0Afunction%20Something(String%20signal)%20%7B%20%7D">Test it</a>

I tried to add parentheses as @disnet says on #37 but an error is produced since commas are placed between identifiers. <a href="http://sweetjs.org/browser/editor.html#macro%20expand_params%20%7B%0A%20%20rule%20%7B%20($param%20...)%20%7D%20=%3E%20%7B%20$param%20...%20%7D%0A%7D%0A%0Amacro%20helper_def%20%7B%0A%20%20rule%20%7B%20($params%20...)%20%7B%20$body%20...%20%7D%20%7D%20=%3E%20%7B%0A%20%20%20%20(function%20($params%20...)%20%7B%20$body%20...%20%7D)%0A%20%20%7D%0A%7D%0A%0Amacro%20def%20%7B%0A%20%20rule%20%7B%20($params%20...)%20%7B%20$body%20...%20%7D%20%7D%20=%3E%20%7B%0A%20%20%20%20helper_def%20(expand_params($params%20...))%20%7B%20$body%20...%20%7D%0A%20%20%7D%0A%7D%0A%0Adef(a,%20b)%20%7B%0A%20%20%20%20return%20a%20+%20b;%0A%7D">Test it</a>

Finally I tried to simplify the issue in the minimal code:

```
macro params_helper {
  rule { $type:ident $name:ident } => { $name }
}
(function(params_helper String signal) { })
```

And this produces

```
(function (params_helper$835, String$836, signal$837) { });
```

So I see two issues here:

First, commas are added between identifiers on function arguments, I don't understand why this is happening but looks reported at #63 is there a plan to fix it?

Second, function parameters macros are not expanded. I see some issues related to this #37, #103 and #120, but there isn't any way to do it? no work around? not even with procedural macros?

It annoys me because since the first time I heard about sweet.js I thought the main possibilities were on function arguments. Anyway I think it's an amazing job and I'm sure it will be part of tomorrow's day to day javascript.

**Comment by mtom55** [comment]
I notice this code no longer works with the latest version of sweet.js... any idea on what the syntax changes should be?

**Comment by gabejohnson** [comment]
@mtom55 this code shouldn't work with sweet.js < v1.0

See #516
