### ISSUE TITLE
Unknown statement type: ClassDeclaration

### ISSUE THREAD

**Issue by jlongster** [sweet-js/sweet-core#261]
Seems like we can't use `class` anymore.

```
class Foo {
  bar() {
    return 1 + 2;
  }
}
```

```
$ sjs foo.js

/Users/james/projects/es6-macros/node_modules/sweet.js/node_modules/escodegen/escode
gen.js:2009                                                                        
            throw new Error('Unknown statement type: ' + stmt.type);
                  ^
Error: Unknown statement type: ClassDeclaration
    at generateStatement (/Users/james/projects/es6-macros/node_modules/sweet.js/nod
```

**Comment by jpdery** [comment]
Still having this issue when there's the `class` keyword somewhere in the output. However, it seems that updating to escodegen 1.4.x fix the issue. Any reasons escodegen is still 1.2.x ?

**Comment by disnet** [comment]
I updated escodegen in the es6-modules branch so it'll land with modules.

**Comment by jayphelps** [comment]
@disnet is master incompatible with the same upgraded escodegen? Curious if we could get this `ClassDeclaration` passthrough working and out, without being held back by es6-modules?

**Comment by disnet** [comment]
@jayphelps it was. I just cherry picked the parser work from es6-modules (easier than I thought it was going to be) and updated escodegen. Class and related should be working, let me know if it all looks good to you.
