### ISSUE TITLE
implement infix macro forms

### ISSUE THREAD

**Issue by disnet** [sweet-js/sweet-core#34]
Using ideas from [honu](http://www.cs.utah.edu/plt/publications/gpce12-rf.pdf) I think we can implement infix operator macros.

**Comment by polkovnikov-ph** [comment]
Mixfix notation would be so much better, you know. Currently I see no way to implement neither `var x = [1..5];` nor `var x = 1 to 5;`

**Comment by natefaubion** [comment]
@polkovnikov-ph Why do you need mixfix for that? You aren't restricted to symbolic names for operators, you can use regular identifiers like `to` when defining an operator. The `..` case is problematic due to the way JS reads numeric literals.
