### ISSUE TITLE
Regex in macros

### ISSUE THREAD

**Issue by iffsid** [sweet-js/sweet-core#436]
I notice that the documentation talks about regexes in the readtables and their extensions, but is there an example of how one could use it in macros -- how to use it in the pattern match and how to refer to the matches in the template? Apologies in advance if I've misunderstood or missed something there. :-)

**Comment by iffsid** [comment]
One particular case where a separate check with macros won't work is when the match is allowed with *anything* for a prefix or suffix. 

Consider for example the case where we convert js stype method access to a schemeified version; i.e
`(.bar foo)` gets converted to `foo.bar`. Normally, patterns of the form `(fn args)` get expanded to `fn(args)`, but in this case, when the first char in the function name starts with `.`, we want to do something different in the expansion.

One would imagine that a rule case, like the following, would help
~~~~ js
...
case {_ ($name:./\([^.]+\)/ $obj) } => { return #{ $obj.$name$1 }}
...
~~~~
by using a regexp to catch the specific cases where the name is an identifier beginning with a `.` and then using the regexp matched group within the template body.

**Comment by natefaubion** [comment]
This is basically what `macroclass` is for:

```js
macroclass dot_ident {
  rule { . $name:ident }
}

macro sexp {
  rule { ($fn:dot_ident $arg) } => { $arg.$fn$name() }
  rule { ($fn:ident     $arg) } => { $fn($arg) }
}

sexp (foo bar)
sexp (.foo bar)
```
```js
foo(bar);
bar.foo();
```

You can reference the submatch components. In this case `$fn$name`. Identifiers can't start with a `.` (its a separate token) so it doesn't really make sense to use a regular expression.

**Comment by iffsid** [comment]
Ah, I see. Thanks!
I thought the space in setting up the macroclass would be significant, in that it would somehow need to be present in the pattern, that's why I didn't go down that route.
