### ISSUE TITLE
Update import statement in Class example given in Sweet Tutorial

### ISSUE THREAD

**Issue by manisuec** [sweet-js/sweet-core#701]
In my system,

npm ls --depth=1
/xxxx/xxxx/work/sweetjs
`-- sweet.js@3.0.5
  +-- @sweet-js/cli@3.0.4
  `-- @sweet-js/core@3.0.4

I was trying the class example given at http://www.sweetjs.org/doc/1.0/tutorial.html#_sweet_class
I was getting below error

Error: Cannot find module 'sweet.js/helpers' from '/xxxx/xxxxx/work/sweetjs'

Updating the import command as below made this example work
import { unwrap, isIdentifier } from 'sweet-core/helpers.js' for syntax;

**Comment by disnet** [comment]
Sorry, more fallout from the re-org. Should have a fix at sweet-js/sweet-shell#2.

Thanks for taking the time to report!
