### ISSUE TITLE
import statements missing in output

### ISSUE THREAD

**Issue by gabejohnson** [sweet-js/sweet-core#727]
input
```js
// a.js
export var a = 42;

// b.js
import { a } from './a';
```
output
```js
```

**Comment by gabejohnson** [comment]
@disnet any ideas on this?

**Comment by disnet** [comment]
are you running sweet on `b.js`? We aren't bundling (yet) so unsurprising you get empty output.

**Comment by gabejohnson** [comment]
Yes. On `b.js` but this was my attempt at a minimal repro. If you try to compile any of the stuff at https://github.com/gabejohnson/fantasy-interfaces you'll see what I'm talking about.

**Comment by disnet** [comment]
Oh! As the title to this issue implies the import statement is missing. Sorry, my brain completely missed that.

Yes, I think I know exactly what's going wrong. I'll get a fix together.
