### ISSUE TITLE
Is there any way to import node stdlib modules?

### ISSUE THREAD

**Issue by lujiajing1126** [sweet-js/sweet-core#730]
something like `import path from 'path' for syntax;`

I found a Error while importing modules like `path`

`Error: ENOENT: no such file or directory, open 'path'`

**Comment by gabejohnson** [comment]
Is `path` an installed module?  If not, you have to use a relative path
```js
import path from './path' for syntax;
```

**Comment by lujiajing1126** [comment]
I mean here `path` is a built-in node stdlib. How can I install that?

**Comment by lujiajing1126** [comment]
Ah, I found it's feasible to import `path` from an external file which could be imported relatively as for syntax.

Thx.

**Comment by disnet** [comment]
Not yet. At the moment the only modules you can import `for syntax` must have a `'lang sweet.js'` directive. The remaining module work is being tracked at #633 so I'll close this issue.
